### ISSUE TITLE
string formatting error when running install

### ISSUE THREAD

**Issue by havok2063** [sdss/sdss_install#11]
When attempting to run `sdss_install` I get the following string formatting error.

```
sdss_install -G tree master
/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/__init__.py:31: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(open(os.path.dirname(__file__) + '/etc/{0}.yml'.format(NAME)))
sdssinstall - ERROR - Unable to authorize the GrqphQL client using the key 'SDSS_GITHUB_KEY'.
sdssinstall - ERROR - Unable to set the directory from the environmental variable KeyError('SDSS_INSTALL_GRAPHQL_DIR').
sdssinstall - ERROR - Unable to set the GraphQL query file.
graphql_dir = None
parameters = {
 "organization_name": "sdss",
 "repository_name": "tree",
 "version": false,
 "query_file_name": "repositories",
 "pagination_flag": null,
 "end_cursor": null,
 "has_next_page": null
}
Traceback (most recent call last):
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/bin/sdss_install", line 17, in <module>
    install.set_ready()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install/Install.py", line 136, in set_ready
    if self.install5: self.install5.set_ready()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Install5.py", line 95, in set_ready
    options=self.options)
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Repositories.py", line 30, in get_repository_names
    self.set_repositories()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Repositories.py", line 39, in set_repositories
    self.set_repository_data()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Repositories.py", line 84, in set_repository_data
    self.set_repository_payload()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Repositories.py", line 95, in set_repository_payload
    self.store.set_data(query_parameters=self.query_parameters)
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/application/Store.py", line 31, in set_data
    self.set_query()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/application/Store.py", line 42, in set_query
    self.client.set_query(parameters=self.query_parameters)
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/application/Client.py", line 66, in set_query
    self.query.set_string()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/application/Query.py", line 52, in set_string
    % (self.file,self.graphql_dir))
TypeError: not all arguments converted during string formatting
```

**Comment by havok2063** [comment]
Reattempting after recent updates now gives this error

```
sdssinstall - ERROR - Unable to set_repository_edges_and_page_info
sdssinstall - ERROR - Unable to set_repository_list
Traceback (most recent call last):
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/bin/sdss_install", line 17, in <module>
    install.set_ready()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install/Install.py", line 136, in set_ready
    if self.install5: self.install5.set_ready()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Install5.py", line 98, in set_ready
    options=self.options)
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Repositories.py", line 30, in get_repository_names
    self.set_repositories()
  File "/Users/Brian/Work/github_projects/sdss/sdss_install/python/sdss_install/install5/Repositories.py", line 43, in set_repositories
    if self.page_info['hasNextPage']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by havok2063** [comment]
This issue remains.  To replicate the above error
1. comment out the `SDSS_INSTALL_GRAPHQL_DIR` environment variable in the `sdss_install` module files.
2. run `sdss_install -G -F tree master`

This issue is relevant for users bypassing the bootstrap installer.  Related to #12, #7.
